[GH-32] Add command autocomplete
mattermost/mattermost-plugin-jenkins pull request #43
Opened 2020-10-05 21:32 UTC by nathanaelhoun

#### Summary

- [x] Add slash command autocomplete
![Peek 2020-10-05 23-30](https://user-images.githubusercontent.com/45119518/95134307-f398d100-0762-11eb-8951-abdb5d9075c5.gif)

#### Ticket Link

Closes #32

2020-10-05 21:32 UTC, mattermod commented
Hello @nathanaelhoun,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-05 22:44 UTC, aaronrothschild approved these changes
Looks good to me @nathanaelhoun thanks for your contribution - this will certainly make the command easier to use!

2020-10-08 16:41 UTC, mickmister requested changes
Great work @nathanaelhoun! I have a few requests regarding grammar, and a request for alphabetizing the commands.

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	connect.AddTextArgument("Your username of Jenkins", "[username]", "")
```suggestion
	connect.AddTextArgument("The username of your Jenkins account", "[username]", "")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	connect.AddTextArgument("You API token from Jenkins", "[API token]", "")
```suggestion
	connect.AddTextArgument("Your API token from Jenkins", "[API token]", "")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	createjob := model.NewAutocompleteData("createjob", "", "Create a Jenkins job using contents of config.xml")
```suggestion
	createjob := model.NewAutocompleteData("createjob", "", "Create a Jenkins job using the contents of a config.xml file")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	connect := model.NewAutocompleteData("connect", "[username] [APIToken]", "Connect to your Jenkins account")
```suggestion
	connect := model.NewAutocompleteData("connect", "[username] [APIToken]", "Connect your Mattermost account to your Jenkins account")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	disconnect := model.NewAutocompleteData("disconnect", "", "Disconnect from your Jenkins account")
```suggestion
	disconnect := model.NewAutocompleteData("disconnect", "", "Disconnect your Mattermost account from your Jenkins account")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	build := model.NewAutocompleteData("build", "[jobname]", "Trigger a build for the giben job")
```suggestion
	build := model.NewAutocompleteData("build", "[jobname]", "Trigger a build for a given job")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	abort.AddTextArgument("Job you want to abort a build to", "[jobname]", "")
```suggestion
	abort.AddTextArgument("Job associated with the build you want to abort", "[jobname]", "")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	plugins := model.NewAutocompleteData("plugins", "", "Get a list of installed plugins on Jenkins server")
```suggestion
	plugins := model.NewAutocompleteData("plugins", "", "Get a list of installed plugins on the Jenkins server")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	help := model.NewAutocompleteData("help", "", "Find help related to the syntaxc of the slash commands")
```suggestion
	help := model.NewAutocompleteData("help", "", "Find help related to the syntax of the slash commands")
```

2020-10-08 16:41 UTC, mickmister commented on server/command.go
> +	jenkins.AddCommand(help)
Can these be added in alphabetical order, so they are listed that way in the UI?

2020-10-08 17:12 UTC, nathanaelhoun commented
Thanks @mickmister for the suggestions, I still need to improve my English!
I have adressed your requests :D

2020-10-08 19:09 UTC, mickmister approved these changes
LGTM :+1:  Thanks @nathanaelhoun!

2020-10-09 14:45 UTC, iomodo approved these changes
LGTM! Thanks for the contribution @nathanaelhoun !

2020-10-15 19:29 UTC, DHaussermann approved these changes
Tested and paseed
- Tested all options have been included in auto-complete and are functional 
- Tested that auto-complete options work on mobile
- No issues found.
LGTM!

Thanks @nathanaelhoun for adding this improvment!

2020-10-16 11:02 UTC, merged