GH-30 initial integration of golangci-lint
mattermost/mattermost-plugin-jenkins pull request #44
Opened 2020-10-09 09:54 UTC by hectorgabucio

#### Summary

Integrates GolangCI-Lint in mattermost jenkins plugin. 
#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-jenkins/issues/30

2020-10-09 09:54 UTC, mattermod commented
Hello @hectorgabucio,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-09 10:12 UTC, hanzei requested changes
Thanks for the contribution :+1: 

Plugins use `p.API.Log*` instead of `log`. See https://developers.mattermost.com/extend/plugins/server/reference/#API.LogWarn for the docs. Would you please change that?

2020-10-09 10:12 UTC, hanzei commented on server/api.go
> +		log.Println("Error sending job creation request", err)
Please use `p.API.LogWarn` instead

2020-10-09 10:12 UTC, hanzei commented on server/plugin.go
> +		log.Println("Error registering Jenkins custom command", cmdErr)
Same here

2020-10-09 17:20 UTC, hanzei approved these changes
One nit pick, the rest looks good :+1:

2020-10-09 17:20 UTC, hanzei commented on server/plugin.go
> +	}
Nit pick: It's idiomatic to use just `err` as variable name if there is no naming conflict.

2020-10-10 14:44 UTC, hanzei approved these changes
Great work :tada:

2020-10-16 11:02 UTC, hanzei commented
@hectorgabucio Could you please resolve the merge conflict?

2020-10-16 21:01 UTC, mickmister approved these changes
Awesome work @hectorgabucio!

2020-10-16 21:59 UTC, hectorgabucio commented
@hanzei the linting failed https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-jenkins/75/workflows/be714750-99de-48fe-927c-f340a226f6ca/jobs/246 maybe we use a newer golang ci version in CI?

2020-10-21 07:32 UTC, hectorgabucio commented
@hanzei @mickmister conflicts resolved and CI passed

2020-10-21 09:56 UTC, hanzei commented
Awesome, thanks @hectorgabucio :+1: 

@DHaussermann There are no function changes in this PR. I've successfully build and deployed the plugin locally. Any additional tests you want to make?

2020-10-22 12:55 UTC, DHaussermann approved these changes
Tested and passed
- Built from this branch - no lint issues with full `make`
- Enabled the plugin and tested that slash commands seem functional
- I will this during end to end testing before the next release for a thorough regression test
LGTM!
Thanks @hectorgabucio for this enhancement!

2020-10-26 23:13 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2020-10-26 23:17 UTC, jasonblais commented
cc @mickmister @hanzei please help with merging if `Automerge` label is unsuccessful.

2020-10-26 23:24 UTC, mattermod commented
Trying to auto merge this PR.

2020-10-26 23:24 UTC, merged

2020-10-26 23:24 UTC, mattermod commented
Pull Request successfully merged
SHA: 75a7f7ddb718adec074e1798f2ffdcc44fd3e3bf