Update community supported README: legal disclaimer
mattermost/mattermost-plugin-jenkins pull request #57
Opened 2023-11-01 15:29 UTC by cwarnermm

Added legal disclaimer to README, as requested by Product.

2023-11-06 11:15 UTC, hanzei requested changes
The repo is not public. This is not needed.

2023-11-07 06:51 UTC, mickmister commented
@hanzei This repo is public

2023-12-08 15:51 UTC, cwarnermm commented on README.md
> +**This repository is community supported and not maintained by Mattermost. Mattermost disclaims any and all liability for integrations, including Third Party Integrations and Mattermost Integrations.
```suggestion
# Disclaimer

**This repository is community supported and not maintained by Mattermost. Mattermost disclaims liability for integrations, including Third Party Integrations and Mattermost Integrations. Integrations may be modified or discontinued at any time.**
```

2023-12-08 15:51 UTC, cwarnermm commented
@hanzei - Legal's updated guidance and language for the legal disclaimer for community-supported integrations has been applied to this PR.

2023-12-12 18:00 UTC, mickmister approved these changes

2023-12-12 18:34 UTC, merged